#ifndef FERRARIENGINE_GLOBAL_H
#define FERRARIENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FERRARIENGINE_LIBRARY)
#  define FERRARIENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FERRARIENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FERRARIENGINE_GLOBAL_H
